import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :notme, NotmeWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Notme.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Opentelemetry

config :notme, :otel_exporter_uri, "http://opentelemetrycollector-prd:4318"
config :notme, :otel_service_name, "elixir-prd"

# Redpanda

config :notme, :redpanda_host, "redpanda-prd"
config :notme, :redpanda_port, 9092
config :notme, :redpanda_topics, ["elixir-prd"]
config :notme, :redpanda_group_default, "group-0"

config :notme, :redpanda_topic_inventory, "pipe-inventory-prd"
config :notme, :redpanda_topic_simple, "pipe-simple-prd"
